// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwsgb9sfIzgPJ-xnxZdUvC2A0DGVbLVI',
    appId: '1:785558129074:web:ceecf582a1c6ae0556bcab',
    messagingSenderId: '785558129074',
    projectId: 'isoftronics',
    authDomain: 'isoftronics.firebaseapp.com',
    storageBucket: 'isoftronics.appspot.com',
    measurementId: 'G-XGD006GGL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4iny-xf2VGd42unHhuLRJGIcAmMqu71M',
    appId: '1:785558129074:android:3908a2b8994f1eef56bcab',
    messagingSenderId: '785558129074',
    projectId: 'isoftronics',
    storageBucket: 'isoftronics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR24rBMwdT2JlMqTyN5kqCxxNMxRMNUX0',
    appId: '1:785558129074:ios:32fdfd824c5f8fe256bcab',
    messagingSenderId: '785558129074',
    projectId: 'isoftronics',
    storageBucket: 'isoftronics.appspot.com',
    iosBundleId: 'com.sivakumar.isoftronicsInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR24rBMwdT2JlMqTyN5kqCxxNMxRMNUX0',
    appId: '1:785558129074:ios:a7ae472be4385f6556bcab',
    messagingSenderId: '785558129074',
    projectId: 'isoftronics',
    storageBucket: 'isoftronics.appspot.com',
    iosBundleId: 'com.sivakumar.isoftronicsInterview.RunnerTests',
  );
}
